# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [7]:
s.split(" ")

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [8]:
planet = "Earth"
diameter = 12742

In [11]:
d = str(diameter)
print(f"The diameter of {planet} is {d} kilometers.")

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [22]:
d["k1"][3]["tricky"][3]["target"][3]

'hello'

# Numpy

In [23]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [25]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [91]:
b = np.array([5,5,5,5,5,5,5,5,5,5])
print(b)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [55]:
#seperate array
for i in range(20,36):
  if i%2 == 0:
    k = np.array([i])
    print(k, end=" ")
  

[20] [22] [24] [26] [28] [30] [32] [34] 

In [58]:
#single array
l = np.arange(20,36,2)
print(l)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [72]:
n = np.arange(0,9).reshape(3,3)
print(n)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [60]:
a = np.array([1,2,3])
b = np.array([4,5,6])
q = np.concatenate((a,b))
print(q)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [73]:
import pandas as pd


In [82]:
students_info = {"Name":["Samanatha","Nazriya","Trisha"],
                 "Profession":["Actress","Actress","Actress"]
                 }
g = pd.DataFrame(students_info)
print(g)

        Name Profession
0  Samanatha    Actress
1    Nazriya    Actress
2     Trisha    Actress


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [87]:
for i in range(1,32):
  print(f"{i} Jan, 2023")
for j in range(1,11):
  print(f"{j} Feb, 2023")


1 Jan, 2023
2 Jan, 2023
3 Jan, 2023
4 Jan, 2023
5 Jan, 2023
6 Jan, 2023
7 Jan, 2023
8 Jan, 2023
9 Jan, 2023
10 Jan, 2023
11 Jan, 2023
12 Jan, 2023
13 Jan, 2023
14 Jan, 2023
15 Jan, 2023
16 Jan, 2023
17 Jan, 2023
18 Jan, 2023
19 Jan, 2023
20 Jan, 2023
21 Jan, 2023
22 Jan, 2023
23 Jan, 2023
24 Jan, 2023
25 Jan, 2023
26 Jan, 2023
27 Jan, 2023
28 Jan, 2023
29 Jan, 2023
30 Jan, 2023
31 Jan, 2023
1 Feb, 2023
2 Feb, 2023
3 Feb, 2023
4 Feb, 2023
5 Feb, 2023
6 Feb, 2023
7 Feb, 2023
8 Feb, 2023
9 Feb, 2023
10 Feb, 2023


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [88]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [90]:
l = pd.DataFrame(lists, index = ["E.no","Name","Salary"])
print(l)

        0    1   2
E.no    1  aaa  22
Name    2  bbb  25
Salary  3  ccc  24
